[package]
name = "common"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4.41", features = ["serde"] }
log = "0.4.27"
serde = { version = "1.0.219", features = ["derive"] }